# Basic_CAD

We are creating a caster.

---
## Table of Contents
* [Table of Contents](#Table-of-Contents)
* [Base](#Base)
* [Mount](#Mount)
* [Fork](#Fork)
* [Tire](#Tire)
* [Wheel](#Wheel)
* [AxleCollarBearings](#AxleCollarBearings)

## Base

### Description

The first assignment is to create the caster base.  The base's dimensions are 200 mm x 120 mm and 8 mm thick.  It has 6 holes 10 mm wide and 20 mm from the edge equally spaced along the edges. There is also a large hole around the center point that has a diameter of 25mm.

### Evidence
[Have a link to my Onshape](https://cvilleschools.onshape.com/documents/493463e1e1a526fb559e972d/w/8847d48b6788f1b2821659f2/e/52c6d9218d9e03f7c28bec72)

### Image
This is how you will write image code for INTERNALLY STORED images on your repo.   just FYI.
~~~
<img src="images/Base.jpg" alt="The Base" width="200">
~~~
<img src="https://github.com/jmuss07/Basic_CAD/blob/master/Base.png?raw=true" height="500">

### Reflection





The base was fairly simple to complete. The only challenging part was adding a pattern for the holes, but now that I have it figured out, it's actually pretty simple!

---


## Mount

### Description
The next part to complete was the mount. For this, we were supposed to create a square extrusion that was 120mmm X 120mm, with as height of 8mm. It also has four holes that are 80mm apart with a diameter of 10mm. These holes are also 20mm from the edge. There is also a large hole in the center that has a diameter of 25mm.

### Evidence
[Have a link to my Onshape](https://cvilleschools.onshape.com/documents/493463e1e1a526fb559e972d/w/8847d48b6788f1b2821659f2/e/52c6d9218d9e03f7c28bec72)

### Image
<img src="https://github.com/jmuss07/Basic_CAD/blob/master/Mount.png?raw=true" height="500">

### Reflection
This part was also fairly simple to complete, and I honestly did not have any trouble with it.
---


## Fork

### Description1
The fork consists of a circular base that is 80mm in diameter, and is extruded 8mm. On this circular base are two rectangles, each 15mm from the center point of the circle,and each having a width of 5mm, a length of 40mm, and a height of 75mm. Both rectangles have 1 mm fillets around all edges, with the corners having a 15mm fillet, and the bottom edge of the rectangles having a 4mm fillet all around, as well as a hole that is 10mm from the top adge and 15mm in diameter going through both. There is also a circular shaft with an outer diameter of 20mm, an inner diameter of 15mm, and a height of 65mm protruding from the opp[osite end of the circular base.
### Evidence
[Have a link to my Onshape](https://cvilleschools.onshape.com/documents/493463e1e1a526fb559e972d/w/8847d48b6788f1b2821659f2/e/52c6d9218d9e03f7c28bec72)
### Image
<img src="https://github.com/jmuss07/Basic_CAD/blob/master/Fork.png?raw=true" height="500">
### Reflection

This was also a simple part to complete, and was actually quite enjoyable to work on.
---


## Tire

### Description
This part is made up of a quadrilateral that has a bottom length of 20mm, and is 10° from the center point. The top edge is 110mm from the horizontal construction line, and the bottom edge is 80mm from the horizontal construction line. This shape is then revolved around the front plane, and completed with an 8mm fillet on both edges.
### Evidence
[Have a link to my Onshape](https://cvilleschools.onshape.com/documents/493463e1e1a526fb559e972d/w/8847d48b6788f1b2821659f2/e/52c6d9218d9e03f7c28bec72)
### Image
<img src="https://github.com/jmuss07/Basic_CAD/blob/master/Tire.png?raw=true" height="500">
### Reflection
Although this part seems simple, I had trouble making sure that the top and bottom edges were dimensioned properly. Other than the dimensioning of the initial shape, creating the reast of the tire is easy.
---


## Wheel

### Description
The wheel was started with a series of three rectangles. These rectangles were then revolved around the horizantal construction line. There are also five cuts made in order to create spokes. Each cut has a bottom radius of 18mm, and a top radius of 30mm, and is based off of two lines that branch from the midpoint and are 60° apart.
### Evidence
[Have a link to my Onshape](https://cvilleschools.onshape.com/documents/493463e1e1a526fb559e972d/w/8847d48b6788f1b2821659f2/e/52c6d9218d9e03f7c28bec72)
### Image
<img src="https://github.com/jmuss07/Basic_CAD/blob/master/Wheel.png?raw=true" height="500">
### Reflection
This part used many of the skills that were practiced in the previous parts. Due to this, I found it less challenging than the tire.
---


## AxleCollarBearings

### Description
This part consists of a cylinder with two shallow slices, one on each end. There is also a collar on one end of the axel, wich is made up of a circle with a diameter of 15mm. There is a small hole in the middle of one of the sides of the collar, which has a diameter of 3mm.
### Evidence
[Have a link to my Onshape](https://cvilleschools.onshape.com/documents/493463e1e1a526fb559e972d/w/8847d48b6788f1b2821659f2/e/52c6d9218d9e03f7c28bec72)
### Image
<img src="https://github.com/jmuss07/Basic_CAD/blob/master/Axle,collar,bearing.png?raw=true" height="500">
### Reflection
These parts were relatively simple, and utilised the "use" feature frequently. However, I was confused at first as to how to add the hole, though this problem was resolved once I looked up the problem.
---
